- name: Cambiar configuración de red
    template:
      src: interfaces
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644
    notify:
      - reboot

- name: Añadir clave pública ssh
  template:
    src: authorized_keys
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: '0600'