Vagrant.configure("2") do |config|
  config.vm.define :dns do |dns|
      dns.vm.box = "debian/bullseye64"
      dns.vm.hostname = "crivero.iesgn.org"
      dns.vm.synced_folder ".", "/vagrant", disabled: true
      dns.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.0.0.2",
          :libvirt__forward_mode => "veryisolated"
      dns.vm.provision "shell", run: "always", inline: <<-SHELL
        apt update && apt upgrade -y
        sysctl -w net.ipv4.ip_forward=1
        iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -j MASQUERADE
      SHELL
    end
  config.vm.define :cliente do |cliente|
      cliente.vm.box = "debian/bullseye64"
      cliente.vm.hostname = "cliente.iesgn.org"
      cliente.vm.synced_folder ".", "/vagrant", disabled: true
      cliente.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.0.0.20",
          :libvirt__forward_mode => "veryisolated"
      cliente.vm.provision "shell", run: "always", inline: <<-SHELL
          ip r del default
          ip r add default via 10.0.0.2
          echo "10.0.0.21 www.iesgn.org departamentos.iesgn.org" >> /etc/hosts
      SHELL
    end
    config.vm.define :servidorweb do |servidorweb|
      servidorweb.vm.box = "debian/bullseye64"
      servidorweb.vm.hostname = "servidorweb.iesgn.org"
      servidorweb.vm.synced_folder ".", "/vagrant", disabled: true
      servidorweb.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.0.0.21",
          :libvirt__forward_mode => "veryisolated"
      servidorweb.vm.provision "shell", run: "always", inline: <<-SHELL
          ip r del default
          ip r add default via 10.0.0.2
          apt update && apt upgrade -y
      SHELL
    end
    config.vm.define :dns2 do |dns2|
        dns2.vm.box = "debian/bullseye64"
        dns2.vm.hostname = "crivero-ns.informatica.iesgn.org"
        dns2.vm.synced_folder ".", "/vagrant", disabled: true
        dns2.vm.network :private_network,
          :libvirt__network_name => "red_privada1",
          :libvirt__dhcp_enabled => false,
          :ip => "10.0.0.5",
          :libvirt__forward_mode => "veryisolated"
        dns2.vm.provision "shell", run: "always", inline: <<-SHELL
          apt update && apt upgrade -y
          ip r del default
          ip r add default via 10.0.0.2
        SHELL
    end   
end