Vagrant.configure("2") do |config|
    config.vm.define :router do |router|
      router.vm.box = "debian/bullseye64"
      router.vm.hostname = "Router" # El nombre de la máquina 
      router.vm.network :public_network, # Indicamos el tipo de red 
        :libvirt__network_name => "red_publica", # Le damos un nombre 
        :dev => "br0", # Indica que se conecte a ese Switch virtual que hemos creado 
        :type => "bridge",
        :mode => "bridge"
      router.vm.network :private_network,
        :libvirt__network_name => "muy_aislada",
        :libvirt__dhcp_enabled => false,
        :ip => "10.0.0.1",
        :libvirt__forward_mode => "veryisolated"
    end
    config.vm.define :cliente do |cliente|
      cliente.vm.box = "debian/bullseye64"
      cliente.vm.hostname = "Cliente"
      cliente.vm.network :private_network,
        :libvirt__network_name => "muy_aislada",
        :libvirt__dhcp_enabled => false,
        :ip => "10.0.0.2",
        :libvirt__forward_mode => "veryisolated"
    config.vm.synced_folder ".", "/vagrant", disabled: true  # No queremos que instale un servidor NFS 
    end
end